image: vvakame/review
env:
  - LANG=en_US.UTF8
script:
  - ruby --version
  - gem list review
  - npm install -g grunt-cli
  - npm install
  - grunt clean pdf
notify:
  email:
    recipients:
      - vvakame@gmail.com
